import { labScenario } from './scenarios'
import { reservoirHeight } from './geometry'

export type SceneKind = 'atlas'|'vortex'|'zeta'|'protein'|'binding'|'crystal'|'agents'|'metrology'|'motor'|'reservoir'
export type Settings = Record<string, number>
export type Control = { key:string; label:string; min:number; max:number; step:number; unit?:string; options?:string[] }
export type Instrument = { title:string; question:string; evidence:string; defaults:Settings; controls:Control[]; presets:{label:string;settings:Settings;note:string}[]; legend:string[]; method:string; source?:string; sourceLabel?:string }
const slider=(key:string,label:string,min:number,max:number,step=1,unit=''):Control=>({key,label,min,max,step,unit})
const choice=(key:string,label:string,options:string[]):Control=>({key,label,min:0,max:options.length-1,step:1,options})
const toggle=(key:string,label:string)=>choice(key,label,['Off','On'])
export const instruments:Record<SceneKind,Instrument>={
 atlas:{title:'The permission boundary',question:'Where does access become a result?',evidence:'Conceptual map',defaults:{stage:0,spread:1,links:1},controls:[choice('stage','Trace a stage',['Whole system','Access','Proposals','Verification','Deployment']),slider('spread','Separation of stages',.6,1.4,.05,'×'),toggle('links','Dependency paths')],presets:[{label:'The whole system',settings:{stage:0,spread:1,links:1},note:'Follow the gold path from access to deployment. The rings are stages, not market shares.'},{label:'The narrow gate',settings:{stage:3,spread:1.3,links:1},note:'Verification remains a separate obligation even when proposals are abundant.'},{label:'Beyond the lab',settings:{stage:4,spread:1.1,links:1},note:'A checked claim must still meet the constraints of a real setting.'}],legend:['Gold · selected path','Cyan · proposals','Violet · verification'],method:'Original conceptual dependency map. Node counts and spacing have no quantitative meaning. Selecting a stage changes emphasis, not a measured success rate.'},
 vortex:{title:'Inside the vortex',question:'Can you separate twisting from concentration?',evidence:'Parametric geometry',defaults:{twist:7,contraction:.65,slice:.55,filaments:40,color:0},controls:[slider('twist','Twist along the axis',0,16,.1,' rad'),slider('contraction','Radial contraction',0,.9,.01),slider('slice','Inspection plane',0,1,.01),slider('filaments','Visible filaments',12,72,4),choice('color','Colour encodes',['Axial position','Filament family'])],presets:[{label:'Rotation only',settings:{twist:7,contraction:0,slice:.55},note:'A twisting bundle can retain the same radius throughout its length.'},{label:'Concentration',settings:{twist:7,contraction:.65,slice:.7},note:'The amber section measures the radius at one position. It remains finite.'},{label:'Tight winding',settings:{twist:14,contraction:.85,slice:.85},note:'An arresting shape is not evidence of a singularity. These curves do not solve a fluid equation.'}],legend:['Spectrum · geometric coordinate','Gold · selected section','Violet · axis'],method:'r(s)=2.5(1−cs), θ(s)=θ₀+τs, y(s)=5s−2.5, 0≤s≤1. c and τ are geometry controls, not viscosity or time. Neither a Navier–Stokes solver nor a depiction of the proposed proof.'},
 zeta:{title:'The critical strip',question:'What changes when you leave the critical line?',evidence:'Computed function',defaults:{sigma:20,height:2.3,window:0,wire:0},controls:[slider('sigma','Real coordinate σ',0,40,1),slider('height','Height exaggeration',.8,4,.1,'×'),choice('window','Imaginary interval t',['10–30','10–18','18–24','24–30']),toggle('wire','Surface mesh')],presets:[{label:'Critical line',settings:{sigma:20,window:0,height:2.3,wire:0},note:'The gold trace follows σ=½. The three marked zeros are known zeros in this finite interval.'},{label:'Move off line',settings:{sigma:30,window:0,height:2.3},note:'Compare the selected cyan trace with the gold critical line. A finite plot cannot settle the hypothesis.'},{label:'First zero',settings:{sigma:20,window:1,height:3.1},note:'Zoom into the neighbourhood of t≈14.134725. The dense 2D critical-line samples resolve the trough more closely than the surface mesh.'}],legend:['Gold · σ=½','Cyan · selected σ','Surface · log(1+|ζ|)'],method:'mpmath at 35 decimal digits. Surface grid: 41×121; dense critical line: 1,201 samples. Height is min(1.8, log(1+|ζ|)) times the display exaggeration. Linked plot reports untransformed magnitude. The domain excludes the pole.',source:'/synaptic/intelligence-without-permission/zeta.json',sourceLabel:'Computed samples · JSON'},
 protein:{title:'Prediction meets structure',question:'Where do the aligned structures disagree?',evidence:'Experimental + predicted',defaults:{layout:0,color:1,residue:64,vectors:1,trace:0},controls:[choice('layout','Comparison',['Superimposed','Side by side']),choice('color','Prediction colour',['Confidence','Displacement','Sequence position']),slider('residue','Inspect residue',1,129,1),toggle('vectors','Displacement vectors'),choice('trace','Representation',['Backbone tubes','Cα atoms + bonds'])],presets:[{label:'Compare the fold',settings:{layout:0,color:1,vectors:1,trace:0,residue:64},note:'The structures have already been aligned by least squares. The spectrum reports Cα displacement in Å.'},{label:'Inspect confidence',settings:{layout:1,color:0,vectors:0,residue:1},note:'pLDDT is a model confidence score. It is not a measured probability that an experimental coordinate is correct.'},{label:'Follow the chain',settings:{layout:0,trace:1,color:1,vectors:1,residue:100},note:'Move the residue selector or click a Cα sphere. The chart and inspection readout follow the same residue.'}],legend:['Cyan · experiment','Gold→violet · displacement','Selected Cα · white'],method:'PDB 1LYZ chain A residues 1–129; AlphaFold DB P00698 residues 19–147. Proper-rotation least-squares alignment of 129 sequence-identical Cα atoms. In the superimposed view, vectors join the aligned coordinates at true relative scale; side-by-side connectors link residue identity across the separated structures. Smooth tubes interpolate Cα coordinates; atom-and-bond mode uses the original points. These are not secondary-structure assignments.',source:'/synaptic/intelligence-without-permission/protein.json',sourceLabel:'Aligned coordinates & provenance'},
 binding:{title:'The geometry of contact',question:'Which atoms are actually close to the ligand?',evidence:'Experimental coordinates',defaults:{cutoff:4,context:1,contacts:1,atom:1,style:0},controls:[slider('cutoff','Proximity threshold',2,4,.1,' Å'),toggle('context','Protein backbone'),toggle('contacts','Neighbouring protein atoms'),slider('atom','Inspect ligand atom',1,16,1),choice('style','Atom scale',['Ball and stick','Space-filling emphasis'])],presets:[{label:'Find the pocket',settings:{cutoff:4,context:1,contacts:1,style:0,atom:1},note:'The ligand sits inside an experimental structure. Nearby atoms are filtered by a geometric threshold.'},{label:'Tight contacts',settings:{cutoff:3,context:0,contacts:1,style:0,atom:4},note:'Reducing the threshold removes more distant neighbours. Dashed connectors indicate proximity, not covalent bonds.'},{label:'Inspect the ligand',settings:{cutoff:4,context:0,contacts:0,style:1,atom:9},note:'Select a ligand atom to see its nearest stored protein neighbour. This is not a binding-affinity calculation.'}],legend:['Gold · ligand carbon','Blue/red · nitrogen/oxygen','Violet · protein neighbours'],method:'PDB 1STP, selected chain A and BTN ligand. Stored neighbourhood contains atoms within 4 Å of any ligand atom. Smaller thresholds are calculated from the same coordinates. Display radii are illustrative. Ligand connectors join atoms less than 1.9 Å apart for orientation; no bond order is assigned. Proximity does not establish a chemical bond.',source:'/synaptic/intelligence-without-permission/binding.json',sourceLabel:'PDB coordinates & provenance'},
 crystal:{title:'One cell. An extended solid.',question:'How does a local arrangement repeat?',evidence:'Experimental crystal',defaults:{repeat:2,cut:1,bonds:1,cells:1,color:1},controls:[slider('repeat','Cells along each axis',1,3,1),slider('cut','Reveal along x',.25,1,.05),toggle('bonds','Nearest-neighbour links'),toggle('cells','Unit-cell boundaries'),choice('color','Colour by',['One element','Two sublattices'])],presets:[{label:'Unit cell',settings:{repeat:1,cut:1,bonds:1,cells:1},note:'The conventional diamond cell has eight periodic sites. Boundary atoms are shared with adjacent cells.'},{label:'Extend the solid',settings:{repeat:3,cut:1,bonds:1,cells:0},note:'The same measured arrangement repeats; it is not a new material prediction.'},{label:'Cut through',settings:{repeat:3,cut:.55,bonds:1,cells:1},note:'The reveal plane exposes the network. Atoms at the edge of this display do not have all periodic neighbours drawn.'}],legend:['Cyan / coral · carbon sublattices','Cyan · nearest neighbours','Fine lines · cell boundaries'],method:'Diamond, COD 9008564 revision 291735. Cubic cell a=3.56679 Å. Nearest-neighbour separation a√3/4. Fractional sites expanded from the deposited CIF. Repeated boundary coordinates are deduplicated for display; clipping is visual only.',source:'/synaptic/intelligence-without-permission/crystal.json',sourceLabel:'Crystal data · CC0'},
 agents:{title:'A million minds. One queue.',question:'What does another agent actually buy?',evidence:'Explicit scenario',defaults:{population:3,unique:25,capacity:500,pass:20},controls:[slider('population','Agents · logarithmic scale',1,6,.1),slider('unique','Distinct candidates',1,100,1,'%'),slider('capacity','Independent checks / day',50,5000,50),slider('pass','Check acceptance assumption',1,100,1,'%')],presets:[{label:'Small laboratory',settings:{population:3,unique:25,capacity:500,pass:20},note:'At this scale the assumed checking capacity can cover all distinct candidates.'},{label:'Million-agent lab',settings:{population:6,unique:25,capacity:500,pass:20},note:'The proposal cloud grows. The verification gate does not. A logarithmic display keeps both visible.'},{label:'Invest in checking',settings:{population:6,unique:25,capacity:5000,pass:20},note:'More independent checks increase provisional acceptances under the chosen pass-rate assumption. Physical validation is still separate.'}],legend:['Cyan · attempted proposals','Violet · checking gate','Gold · provisional acceptances'],method:'One attempt per agent per day; unique=attempts×distinct fraction; checked=min(unique, capacity); accepted=checked×assumed pass fraction. An empty daily queue is assumed at the start. Dots aggregate groups on a logarithmic display; no agent benchmark or discovery forecast is implied.'},
 metrology:{title:'The feedback advantage',question:'What does correction remove—and leave behind?',evidence:'Synthetic error field',defaults:{offset:1.5,rotation:.6,warp:.6,correction:70,mode:0},controls:[slider('offset','Translation error',0,3,.1,' a.u.'),slider('rotation','Rotational error',0,1.5,.05),slider('warp','Unmodelled distortion',0,1.5,.05),slider('correction','Known-error correction',0,100,1,'%'),choice('mode','Error field',['Before correction','After correction'])],presets:[{label:'Measure',settings:{offset:1.5,rotation:.6,warp:.6,correction:0,mode:0},note:'Coloured vectors show the synthetic displacement field on a wafer-shaped grid. Vectors are exaggerated for visibility.'},{label:'Correct known error',settings:{offset:1.5,rotation:.6,warp:.6,correction:90,mode:1},note:'Correction removes a chosen fraction of translation and rotation. The unmodelled distortion remains.'},{label:'The residual floor',settings:{offset:1.5,rotation:.6,warp:1.2,correction:100,mode:1},note:'Even perfect correction of the known terms leaves a residual. Better feedback requires a better model and measurements.'}],legend:['Spectrum · error magnitude','Cyan · nominal sample grid','Gold · measurement path'],method:'Synthetic unitless field on a unit disk: e=(b−ry+w sin(πx)cos(πy), rx+w cos(πx)sin(πy)). Correction scales only b and r by (1−c). RMS is computed over the displayed sample locations. This is not an ASML process model or a nanometre accuracy claim.'},
 motor:{title:'Intelligence meets the machine',question:'What does an attractive design still have to prove?',evidence:'Engineering schematic',defaults:{explode:0,angle:25,housing:1,cutaway:1,coils:1},controls:[slider('explode','Exploded separation',0,1,.05),slider('angle','Rotor orientation',0,360,5,'°'),toggle('housing','Outer housing'),toggle('cutaway','Housing cutaway'),toggle('coils','Copper windings')],presets:[{label:'Assembled',settings:{explode:0,angle:25,housing:1,cutaway:1,coils:1},note:'A generic assembly exposes the rotor, stator, windings and bearings. It is not a proprietary Dyson motor.'},{label:'Exploded assembly',settings:{explode:1,angle:25,housing:0,cutaway:1,coils:1},note:'Separating the components reveals the interfaces a physical design must reconcile.'},{label:'Mechanical clearance',settings:{explode:0,angle:85,housing:0,coils:0},note:'Geometry is visible; torque, efficiency, acoustic behaviour and service life still require appropriate models and tests.'}],legend:['Cyan · rotor','Copper · windings','Violet · shaft / bearings'],method:'Original generic six-stator-sector schematic in arbitrary display units. Rotor orientation and exploded separation are presentation controls, not a dynamic simulation. No electromagnetic, thermal, acoustic, efficiency or manufacturability result is calculated.'},
 reservoir:{title:'The ground does not negotiate',question:'How much does an alternative geometry change the well?',evidence:'Synthetic geology',defaults:{alternative:0,section:0,well:-1.45,exaggeration:1,cut:1,material:1},controls:[slider('alternative','Geometry A → B',0,1,.05),slider('section','Section position z',-3,3,.1),slider('well','Well position x',-3.5,3.5,.05),slider('exaggeration','Vertical exaggeration',.6,1.8,.1,'×'),toggle('cut','Reveal the selected section'),choice('material','Geological view',['Horizon surfaces','Sedimentary block'])],presets:[{label:'Interpretation A',settings:{alternative:0,section:0,well:-1.45,exaggeration:1,cut:0},note:'Four synthetic horizons establish a baseline interpretation. The gold line marks the linked cross-section.'},{label:'Interpretation B',settings:{alternative:1,section:0,well:-1.45,exaggeration:1,cut:1},note:'An alternative uplift changes the horizon intersections at the same well. No production forecast follows from this geometry alone.'},{label:'Move the well',settings:{alternative:1,section:1,well:1.8,exaggeration:1.3,cut:1},note:'Move the well and section together. The depth profile uses unexaggerated, arbitrary units.'}],legend:['Gold · selected section','Cyan/violet · horizons','White · well trajectory'],method:'Four synthetic non-intersecting horizons: h=1.2−1.15L+0.28sin(0.65x)cos(0.7z)+0.7a exp[−(x²+z²)/7]. a interpolates two hypothetical geometries. Axes use arbitrary units. Rock textures and bedding are procedural illustrations, not sampled lithology. No field observations, fluid flow, reserves or recovery estimate is represented.'},
}

export type Atom={xyz:number[];element:string;name:string;residue:string;number:number}
export type ScienceData={experimental?:number[][];predicted?:number[][];confidence?:number[];residues?:string[];rmsd_angstrom?:number;backbone?:Atom[];ligand?:Atom[];contacts?:Atom[];fractional_points?:number[][];bonds?:number[][];cell_length_angstrom?:number;real?:number[];imaginary?:number[];values?:number[][];critical_line?:number[][];zeros?:number[]}
const cache=new Map<string,Promise<ScienceData>>()
export function loadInstrumentData(kind:SceneKind):Promise<ScienceData>{
 if(!['zeta','protein','binding','crystal'].includes(kind))return Promise.resolve({})
 const previous=cache.get(kind);if(previous)return previous
 const request=fetch(`/synaptic/intelligence-without-permission/${kind}.json`).then(r=>{if(!r.ok)throw Error(`Missing ${kind} data`);return r.json() as Promise<ScienceData>}).catch(e=>{cache.delete(kind);throw e})
 cache.set(kind,request);return request
}
export const distance=(a:number[],b:number[])=>Math.hypot(...a.map((v,i)=>v-b[i]))
export const fmt=(n:number,digits=1)=>n.toLocaleString('en-US',{maximumFractionDigits:digits})
export function formatControl(c:Control,s:Settings){const v=s[c.key];return c.options?c.options[v]:c.key==='population'?fmt(Math.round(10**v),0):c.key==='sigma'?(v/40).toFixed(3):`${fmt(v,2)}${c.unit||''}`}
export function zetaInterval(s:Settings){return [[10,30],[10,18],[18,24],[24,30]][s.window]}
export function metrologySamples(s:Settings){
 const points:{x:number;y:number;before:number[];after:number[]}[]=[]
 for(let iy=-6;iy<=6;iy++)for(let ix=-6;ix<=6;ix++){const x=ix/6,y=iy/6;if(x*x+y*y>.96)continue;const wx=s.warp*Math.sin(Math.PI*x)*Math.cos(Math.PI*y),wy=s.warp*Math.cos(Math.PI*x)*Math.sin(Math.PI*y);points.push({x,y,before:[s.offset-s.rotation*y+wx,s.rotation*x+wy],after:[(1-s.correction/100)*(s.offset-s.rotation*y)+wx,(1-s.correction/100)*s.rotation*x+wy]})}
 return points
}
export function crystalSites(data:ScienceData,n:number){
 const map=new Map<string,number[]>()
 for(let x=0;x<n;x++)for(let y=0;y<n;y++)for(let z=0;z<n;z++)for(const p of data.fractional_points||[]){const q=[p[0]+x,p[1]+y,p[2]+z];map.set(q.join(','),q)}
 return [...map.values()]
}
export type Reading={label:string;value:string;unit?:string}
export type PlotSeries={name:string;values:number[];color:string}
export type Analysis={readings:Reading[];series:PlotSeries[];x:number[];xLabel:string;yLabel:string;insight:string;selected?:number}
export function analyse(kind:SceneKind,s:Settings,d:ScienceData):Analysis{
 const cyan='#79e0eb',gold='#f2bd7e',violet='#b5a0ef';const series:PlotSeries[]=[];let x:number[]=[],xLabel='',yLabel='',insight='';let readings:Reading[]=[];let selected:number|undefined
 if(kind==='vortex'){x=Array.from({length:81},(_,i)=>i/80);series.push({name:'Radius',values:x.map(t=>2.5*(1-s.contraction*t)),color:cyan});xLabel='Axial fraction s';yLabel='Radius · arbitrary units';selected=Math.round(s.slice*80);readings=[{label:'Section radius',value:fmt(2.5*(1-s.contraction*s.slice),3),unit:'a.u.'},{label:'Exit / entry area',value:fmt(100*(1-s.contraction)**2,1),unit:'%'},{label:'Total turns',value:fmt(s.twist/(2*Math.PI),2)},{label:'Axial sample',value:fmt(s.slice,2)}];insight=`At s=${fmt(s.slice,2)}, the radius is ${fmt(2.5*(1-s.contraction*s.slice),3)}. Twisting changes orientation; contraction changes cross-sectional area. No fluid equation is being solved.`}
 if(kind==='zeta'&&d.values&&d.imaginary){const range=zetaInterval(s);const indices=d.imaginary.map((t,i)=>({t,i})).filter(p=>p.t>=range[0]&&p.t<=range[1]);x=indices.map(p=>p.t);series.push({name:`σ=${(s.sigma/40).toFixed(3)}`,values:indices.map(p=>d.values![p.i][s.sigma]),color:cyan},{name:'σ=0.500 · grid samples',values:indices.map(p=>d.values![p.i][20]),color:gold});if(s.sigma===20&&d.critical_line){const rows=d.critical_line.filter(p=>p[0]>=range[0]&&p[0]<=range[1]);x=rows.map(p=>p[0]);series.splice(0,2,{name:'Critical line · dense samples',values:rows.map(p=>p[1]),color:gold})}xLabel='Imaginary coordinate t';yLabel='|ζ(σ + it)|';const zeros=d.zeros!.filter(t=>t>=range[0]&&t<=range[1]);readings=[{label:'Selected σ',value:(s.sigma/40).toFixed(3)},{label:'Interval',value:`${range[0]}–${range[1]}`,unit:'t'},{label:'Known critical zeros',value:String(zeros.length)},{label:'Surface samples',value:fmt(indices.length*41,0)}];insight=s.sigma===20?'You are on the critical line. A finite set of known zeros is an illustration, not evidence that every nontrivial zero lies here.':'The cyan slice has moved off the critical line. Compare its troughs with the gold reference; height exaggeration changes the scene, not the linked values.'}
 if(kind==='protein'&&d.experimental&&d.predicted){const delta=d.experimental.map((p,i)=>distance(p,d.predicted![i]));x=delta.map((_,i)=>i+1);series.push({name:'Cα displacement',values:delta,color:gold});xLabel='Residue · mature chain';yLabel='Displacement · Å';selected=s.residue-1;readings=[{label:'Aligned Cα RMSD',value:fmt(d.rmsd_angstrom!,3),unit:'Å'},{label:'Selected residue',value:`${d.residues![selected]} ${s.residue}`},{label:'Local displacement',value:fmt(delta[selected],3),unit:'Å'},{label:'Prediction pLDDT',value:fmt(d.confidence![selected],1),unit:'/100'}];insight=`Residue ${s.residue} differs by ${fmt(delta[selected],3)} Å after global alignment. The confidence score and the coordinate discrepancy answer different questions.`}
 if(kind==='binding'&&d.ligand&&d.contacts){const nearest=d.ligand.map(a=>Math.min(...d.contacts!.map(b=>distance(a.xyz,b.xyz))));const contacts=d.contacts.filter(a=>d.ligand!.some(b=>distance(a.xyz,b.xyz)<=s.cutoff));x=nearest.map((_,i)=>i+1);series.push({name:'Nearest stored protein atom',values:nearest,color:gold});selected=s.atom-1;xLabel='Ligand atom · index';yLabel='Nearest distance · Å';readings=[{label:'Ligand atom',value:d.ligand[s.atom-1].name},{label:'Nearest stored neighbour',value:fmt(nearest[s.atom-1],3),unit:'Å'},{label:'Visible neighbours',value:String(contacts.length)},{label:'Threshold',value:fmt(s.cutoff,1),unit:'Å'}];insight=`${contacts.length} stored protein atoms fall within ${fmt(s.cutoff,1)} Å of the ligand. Spatial proximity is not a measurement of affinity or proof of a chemical interaction.`}
 if(kind==='crystal'&&d.fractional_points){const sites=crystalSites(d,s.repeat),visible=sites.filter(p=>p[0]<=s.repeat*s.cut);x=[1,2,3];series.push({name:'Periodic sites',values:x.map(n=>8*n**3),color:gold});xLabel='Cells along each axis';yLabel='Periodic sites · count';selected=s.repeat-1;readings=[{label:'Periodic sites · full block',value:String(8*s.repeat**3)},{label:'Visible boundary-inclusive sites',value:String(visible.length)},{label:'Nearest-neighbour distance',value:fmt(d.cell_length_angstrom!*Math.sqrt(3)/4,4),unit:'Å'},{label:'Conventional cell',value:fmt(d.cell_length_angstrom!,5),unit:'Å'}];insight='Repeating cells expands a known arrangement. Periodic site counts differ from the visible count because adjacent cells share their boundary atoms.'}
 if(kind==='agents'){const agents=Math.round(10**s.population);const q=labScenario({agents,uniqueFraction:s.unique/100,checkCapacity:s.capacity,passRate:s.pass/100,attemptCost:0,checkCost:0,experimentCost:0});x=Array.from({length:51},(_,i)=>1+i/10);series.push({name:'Expected accepted / day',values:x.map(p=>Math.min(10**p*s.unique/100,s.capacity)*s.pass/100),color:gold});xLabel='log₁₀ agents · 1→10, 6→1M';yLabel='Expected accepted / day';selected=Math.round((s.population-1)*10);readings=[{label:'Attempted / day',value:fmt(agents,0)},{label:'Checked / day',value:fmt(q.checked,0)},{label:'Waiting beyond today',value:fmt(q.queued,0)},{label:'Expected accepted / day',value:fmt(q.accepted,1)}];insight=q.queued>0?`The checking gate is saturated. ${fmt(q.queued,0)} distinct candidates exceed today's capacity. Adding agents alone cannot lift the plateau under these assumptions.`:'The checking gate can cover the distinct candidates in this scenario. Increase the population until the acceptance curve reaches its capacity ceiling.'}
 if(kind==='metrology'){const points=metrologySamples(s),rms=(key:'before'|'after')=>Math.sqrt(points.reduce((a,p)=>a+p[key][0]**2+p[key][1]**2,0)/points.length);x=points.map((_,i)=>i+1);series.push({name:'Before',values:points.map(p=>Math.hypot(...p.before)),color:gold},{name:'After',values:points.map(p=>Math.hypot(...p.after)),color:cyan});xLabel='Sample · row-major order';yLabel='Displacement magnitude · a.u.';readings=[{label:'RMS before',value:fmt(rms('before'),3),unit:'a.u.'},{label:'RMS after',value:fmt(rms('after'),3),unit:'a.u.'},{label:'Correction applied',value:fmt(s.correction,0),unit:'%'},{label:'Synthetic samples',value:String(points.length)}];insight='The residual includes the unmodelled distortion. Correcting the known translation and rotation terms does not automatically correct everything a real measurement would reveal.'}
 if(kind==='reservoir'){x=Array.from({length:161},(_,i)=>-4+i/20);for(let l=0;l<4;l++)series.push({name:`Horizon ${l+1}`,values:x.map(t=>reservoirHeight(t,s.section,l,s.alternative)),color:[gold,cyan,violet,'#a4b6c7'][l]});xLabel='x · arbitrary units';yLabel='Height · arbitrary units';selected=Math.round((s.well+4)*20);readings=[{label:'Geometry B contribution',value:fmt(s.alternative*100,0),unit:'%'},{label:'Well / section',value:`${fmt(s.well,2)} / ${fmt(s.section,1)}`},{label:'Top intersection',value:fmt(reservoirHeight(s.well,s.section,0,s.alternative),3),unit:'a.u.'},{label:'Shift from geometry A',value:fmt(reservoirHeight(s.well,s.section,0,s.alternative)-reservoirHeight(s.well,s.section,0,0),3),unit:'a.u.'}];insight='Changing the interpretation changes the well intersections. Vertical exaggeration only changes the display; the linked profile keeps the original units. Geometry alone does not establish recoverable reserves.'}
 if(kind==='motor'){readings=[{label:'Assembly',value:s.explode>.1?'Exploded':'Assembled'},{label:'Rotor orientation',value:String(s.angle),unit:'°'},{label:'Stator sectors',value:'6'},{label:'Performance prediction',value:'Not calculated'}];insight='Every interface carries a physical obligation: clearances, heat rejection, vibration, insulation and a repeatable manufacturing process. A visible assembly does not discharge those obligations.'}
 if(kind==='atlas'){readings=[{label:'Selected stage',value:['All stages','Access','Proposals','Verification','Deployment'][s.stage]},{label:'Map type',value:'Conceptual'},{label:'Evidence gates',value:'Independent'},{label:'Claim',value:'Access ≠ outcome'}];insight=['Intellectual access widens the entrance. The rest of the path remains work.','Access includes models, tools, compute and the ability to ask a useful question.','A proposal is an attempt. Its fluency does not determine its validity.','Verification makes a claim answerable to evidence outside its own generation.','Deployment adds physical, institutional and economic constraints.'][s.stage]}
 return {readings,series,x,xLabel,yLabel,insight,selected}
}

export function sanitizeSettings(kind:SceneKind,input:unknown):Settings{
 const config=instruments[kind],out={...config.defaults};if(!input||typeof input!=='object')return out
 for(const c of config.controls){const value=(input as Settings)[c.key];if(typeof value==='number'&&Number.isFinite(value)){const clamped=Math.max(c.min,Math.min(c.max,value));out[c.key]=Number((c.min+Math.round((clamped-c.min)/c.step)*c.step).toFixed(6))}}
 return out
}
