import manifest from "../../../../docs/plans/intelligence-without-permission/production-manifest.json"
import { SpatialFigure } from "./SpatialFigure"
import { VortexDiagram, VerificationTimeline, FermatTimeline, ProofDependencies } from "./MathFigures"
import { ZetaSlice, ZetaBound, ProteinProjection, BindingProjection, ProteinFunnel, MeasurementAudit } from "./ScienceFigures"
import { CrystalProjection, AlgorithmIdentity, FeedbackComparison } from "./DiscoveryFigures"
import { AgentLab, Coordination, CheckedCost } from "./LabFigures"
import { AccessMap, OutsideResearch, UniversityFunctions, PublicLineage } from "./InstitutionFigures"
import { ResearchAssets, ValuablePiece, MetrologyProjection, MotorProjection, CompanyComparison } from "./EnterpriseFigures"
import { ReservoirStudy, IndustryComparison, PipelineCapacity } from "./IndustryFigures"
import { RemainingClocks, SavingsDistribution, MarketTiming } from "./MarketFigures"
import { DependencyNetwork, AccessFutures, InstitutionActions, ClosingPaths } from "./FutureFigures"

const labels = ["Questions", "Attempts", "Checked results", "Useful changes"]

function Atlas() {
  return <svg viewBox="0 0 1000 355" role="img" aria-label="Four research stages: questions, attempts, checked results and useful changes. More attempts do not imply equal growth in verified outcomes.">
    <defs><linearGradient id="iwp-atlas-line"><stop stopColor="#e7b778"/><stop offset=".5" stopColor="#7ed1d2"/><stop offset="1" stopColor="#b6a1e4"/></linearGradient></defs>
    {labels.map((label,i)=><g key={label}><text x={100+i*260} y="40" textAnchor="middle" className="iwp-svg-title">{label}</text><line x1={100+i*260} x2={100+i*260} y1="65" y2="278" stroke="#314050" strokeDasharray="3 6"/><text x={100+i*260} y="320" textAnchor="middle">{["Who gets to ask?","Who can afford to try?","What survives checking?","Who benefits?"][i]}</text></g>)}
    {[0,1,2].map(stage=>Array.from({length:stage===0?11:6},(_,i)=><path key={`${stage}-${i}`} d={`M ${100+stage*260} ${85+i*(stage===0?17:32)} C ${200+stage*260} ${60+i*20},${280+stage*260} ${80+i*24},${360+stage*260} ${85+i*(stage===0?17:32)}`} fill="none" stroke="url(#iwp-atlas-line)" opacity=".25"/>))}
    {[5,11,4,3].map((n,stage)=>Array.from({length:n},(_,i)=><circle key={`${stage}-${i}`} cx={100+stage*260} cy={85+i*170/Math.max(n-1,1)} r={stage===2?7:5} fill={["#e7b778","#7ed1d2","#b6a1e4","#f2e9d6"][stage]}/>))}
    <path d="M100 170 C205 170 255 170 360 170 S515 170 620 170 S775 170 880 170" stroke="#e7b778" fill="none" strokeWidth="2"/>
    {[100,360,620,880].map(x=><circle key={x} cx={x} cy="170" r="9" fill="#e7b778" stroke="#101e30" strokeWidth="3"/>)}
  </svg>
}

function Capability() {
  const rows = [
    ["Navier–Stokes", "OpenAI internal research system", "Paper + formal artefact released", "Research system not publicly released"],
    ["Fermat formalisation", "Anthropic research system", "Formal proof code released", "Result access ≠ system access"],
    ["Zeta-function bound", "Internal Claude research configuration", "Reported theorem + assessment", "Do not attribute to a retail model"],
    ["Protein design", "Specialised research configuration", "Designs tested in wet labs", "Compute, tools and lab access matter"],
    ["Everyday research assistance", "Publicly offered models", "Literature, code and analysis tasks", "Country, price and capability vary"],
  ]
  return <div className="iwp-table-scroll"><table className="iwp-table"><caption className="sr-only">Research capability and actual access as of 9 September 2026</caption><thead><tr>{["Example","System used","What is available","Access boundary"].map(label=><th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></div>
}

function TaskProfile() {
  const tasks = [
    ["Read", "Find and compare relevant literature", "Check retrieval, attribution and omitted work"],
    ["Build", "Write code, models and candidate proofs", "Run independent tests; inspect assumptions"],
    ["Interpret", "Connect measurements with explanations", "Keep calibration and alternative explanations"],
    ["Experiment", "Propose informative next tests", "Physical execution and validity remain separate"],
    ["Judge", "Choose which questions deserve attention", "Novelty, consequence and responsibility need scrutiny"],
  ]
  return <svg viewBox="0 0 1000 410" role="img" aria-label="Five components of research: reading, building, interpreting, experimenting and judgement. Each needs its own evidence rather than a single intelligence score.">
    <text x="30" y="27" fill="#e7b778">A task, not a title</text><text x="490" y="27">The corresponding burden of proof</text>
    {tasks.map(([name,task,check],i)=><g key={name} transform={`translate(0,${55+i*68})`}><line x1="20" x2="980" y1="55" y2="55" stroke="#314050"/><circle cx="40" cy="16" r="16" stroke="#7ed1d2" fill="none"/><text x="40" y="20" textAnchor="middle">{i+1}</text><text x="75" y="10" className="iwp-svg-title">{name}</text><text x="75" y="34">{task}</text><path d="M435 18h30m-7-5 7 5-7 5" stroke="#e7b778" fill="none"/><text x="490" y="22">{check}</text></g>)}
  </svg>
}

export function Figure({ id }: { id: string }) {
  const metadata = manifest.figures.find(figure => figure.id === id)
  if (!metadata) throw new Error(`Unknown article figure ${id}`)
  let body
  let caption: string
  let method: string
  switch (id) {
    case "V35": body = <DependencyNetwork/>; caption = "A wider ability to generate research does not remove every dependency. Practical alternatives determine how much control a lab has over its work."; method = "Original qualitative network. Provider country lists, EuroHPC access, UNESCO open-science principles and the industry analysis establish different parts of the context. Edges indicate necessary relationships, not ownership shares or measured market concentration."; break
    case "V36": body = <AccessFutures/>; caption = "Broad capability can coexist with either wider choice or concentrated control. The surrounding arrangements influence who can turn a proposal into useful evidence."; method = "Two explicit institutional scenarios. Node counts and positions are schematic, not observations or projections. No probability, forecast date or allegation about a particular provider is encoded."; break
    case "V37": body = <InstitutionActions/>; caption = "The response can begin with a bounded experiment and a clear decision. Measure checked outcomes, useful access and complete costs."; method = "Original recommendations derived from the essay. The measures are proposed criteria, not established causal effect sizes. No universal timetable or staffing reduction is prescribed."; break
    case "V38": body = <ClosingPaths/>; caption = "The opening path returns with its conditions visible. More people can participate meaningfully when a serious attempt has a route to evidence and use."; method = "Narrative synthesis of the mathematics, biology and industry chapters. Links return to the underlying evidence. This figure introduces no additional empirical claim."; break
    case "V32": body = <RemainingClocks/>; caption = "The stage that does not accelerate limits the whole project. Better research can sometimes change that stage too, but the mechanism must be demonstrated."; method = "Serial two-stage accounting on a 100-unit baseline: T = 100(1−f) + 100f/s, where f is the accelerated share and s its speedup. No actual industry duration is represented. Fixed scope, no overlap, queue, rework or change in the other stage. Not a clinical or industrial schedule."; break
    case "V33": body = <SavingsDistribution/>; caption = "Lower research cost can become a lower price, a larger unit margin or both. The size of the effect depends first on research’s share of total cost."; method = "Original accounting scenario: baseline price 100, cost 80. Saving = 80 × research share × reduction; customer saving = saving × pass-through. New cost + unit margin + customer saving = 100. Abstract units, fixed volume and quality; no observed company costs or forecast market shares."; break
    case "V34": body = <MarketTiming/>; caption = "Scientific progress, adoption and market response can happen at different speeds. A new result changes commercial outcomes through specific conditions."; method = "Two qualitative scenarios developed in chapter 14. No dates, probabilities or universal industry-collapse sequence. Distances in the diagram do not encode measured time."; break
    case "V29": body = <ReservoirStudy/>; caption = "A subsurface model is an interpretation. More powerful analysis should help compare alternatives and identify useful observations, rather than erase uncertainty from the picture."; method = "Synthetic educational surfaces: y = 1.2 − 1.15l + 0.28 sin(0.65x) cos(0.7z) + 0.7a exp[−(x²+z²)/7], layers l=0…3, alternative a∈[0,1], x∈[−4,4], z∈[−3,3]. Arbitrary units. The 3D surface uses 65×33 vertices per horizon; solid cut faces add procedural bedding and grain. The linked profile contains 161 points at the selected section z; the static explanation uses z=0. No field observations, permeability, pressure, reserves or flow calculation. Both geometries are invented, not statistically fitted alternatives."; break
    case "V30": body = <IndustryComparison/>; caption = "Five industries, examined through the same questions. Benefits depend on the path from a useful research result to a change in operation."; method = "Explicit scenarios grounded in chapters 5, 11 and 12 and their primary sources. The table is an analytical comparison, not a forecast or a ranking. No probabilities or dates of displacement are assigned."; break
    case "V31": body = <PipelineCapacity/>; caption = "A faster first stage can leave the final output unchanged. Change validation or deployment capacity to see where the queue moves."; method = "Original one-period deterministic accounting. Validated = min(arrivals, validation capacity); deployed = min(validated, deployment capacity). Empty initial queues and all processed candidates pass. Candidates are interchangeable units; actual sectoral workflows contain rejection, feedback and unequal work. Not an empirical productivity forecast."; break
    case "V24": body = <ResearchAssets/>; caption = "The department is a collection of tasks and assets. A challenger needs access to the pieces required for its promise; the incumbent must show how its combination improves the result."; method = "Original task decomposition. Qualitative relationships, not measured automation percentages. Company evidence and distinctions are developed in chapters 10 and 11."; break
    case "V25": body = <ValuablePiece/>; caption = "A smaller lab can compete for one useful contribution. Its success could produce a partnership, a new supplier or stronger competition within the value chain."; method = "Three explicit commercial scenarios. No company, transaction, revenue or market-share outcome is claimed as observed. Dependencies and acceptance tests remain visible."; break
    case "V26": body = <SpatialFigure kind="metrology" fallback={<MetrologyProjection/>} description="Simplified metrology geometry: patterned wafer, illumination and measurement paths."/>; caption = "More capable computation becomes useful through measurements of a physical process. The loop connects a model with the manufacturing conditions it must describe."; method = "Original educational geometry in arbitrary units, informed by ASML’s public computational-lithography and measuring-accuracy explanations. Not a proprietary EUV layout, ray-tracing simulation or calibrated instrument model. The drawn path explains observation, not a specific optical architecture."; break
    case "V27": body = <SpatialFigure kind="motor" fallback={<MotorProjection/>} description="Generic conceptual motor with six stator regions, rotor and shaft."/>; caption = "A motor concept faces several tests at once. A useful product must reconcile electromagnetic behaviour, heat, vibration, control and manufacture."; method = "Original generic geometry: six stator regions, central rotor, shaft and housing, arbitrary dimensions. No Dyson design, material parameters, field solution, efficiency or performance simulation is represented. Dyson’s engineering descriptions provide context only."; break
    case "V28": body = <CompanyComparison/>; caption = "These four companies face different opportunities and constraints. Their documented research activity contradicts a blanket story of passive incumbents."; method = "Company primary sources: ASML 2025 report and technical explanations; IBM’s December 2024 materials-model release; Google DeepMind’s AlphaEvolve publications; Dyson’s research and motor-engineering descriptions. Challenger entries and responses are the essay’s analysis, not company forecasts."; break
    case "V20": body = <AccessMap/>; caption = "Worldwide potential is larger than effective access today. A service-country listing answers only one of the questions facing a researcher."; method = "Six sampled countries checked against official OpenAI and Anthropic API country lists on 9 September 2026. Country markers are approximate label locations, not individual users. Natural Earth public-domain land, equirectangular projection. Grey regions are unassessed. The map does not represent all providers, model capabilities, affordability or restrictions."; break
    case "V21": body = <OutsideResearch/>; caption = "A researcher outside a major institution can approach a partner with a better question and a more complete attempt. Physical evidence and a path to use remain essential."; method = "Explicit hypothetical engineering workflow. No invented person, quotation, field measurement or commercial outcome. The stages identify where digital assistance and local knowledge can complement facilities and independent assessment."; break
    case "V22": body = <UniversityFunctions/>; caption = "The university’s activities face different pressures. Its public role can grow if it makes the contribution behind each function clearer."; method = "Original institutional analysis, not a numerical exposure ranking. The six functions are discussed in chapter 9 with examples of public educational and research infrastructure."; break
    case "V23": body = <PublicLineage/>; caption = "The public work beneath a model is part of the explanation of its success. Institutional criticism should preserve that history."; method = "Selected chains based on the Fermat repository attribution, Lean documentation, AlphaFold and RFdiffusion papers and public structural databases. Arrows indicate contribution, not exclusive causation. This is not a complete intellectual genealogy."; break
    case "V17": body = <AgentLab/>; caption = "A million attempts do not create a million checked results. Increase the worker count and watch the review queue become the binding constraint."; method = "Original accounting scenario: one attempt per agent per day; uniqueness, checking capacity and acceptance are user-controlled, with defaults of 25%, 500 checks/day and 20%. Expected counts are illustrative. 3D dots are aggregate schematic groups, not individual agents or measured discoveries; the numerical flow is provided in 2D."; break
    case "V18": body = <Coordination/>; caption = "Coordination can help or hurt. Correlated answers also contain less independent information than their count suggests."; method = "Study panel: Kim et al., arXiv:2512.08296v3, 260 configurations, six benchmarks. Separate illustration: effective sample size n/[1+(n−1)ρ] for the variance of an equicorrelated mean with equal marginal variances. Not calibrated to agents, not a success-rate or discovery prediction."; break
    case "V19": body = <CheckedCost/>; caption = "Cheap inference can coexist with expensive research. The useful denominator is the checked candidate and the work still needed to test it."; method = "Original illustrative USD accounting, not current commercial pricing. Fixed 1,000 attempts, 25% uniqueness, $2/check, 20% initial acceptance. Costs of physical tests are included but their success is not assumed. All omitted costs are disclosed. Inputs and sums are reproducible in scenarios.ts."; break
    case "V14": body = <SpatialFigure kind="crystal" fallback={<CrystalProjection/>} description="Diamond unit cell, from COD 9008564 experimental structure data."/>; caption = "A unit cell describes a repeating arrangement. A useful material also needs a route to synthesis, relevant measured properties and a practical application."; method = "COD 9008564 revision 291735, Wyckoff (1963), via AMCSD. Cell length 3.56679 Å. Origin site expanded using the CIF’s explicit symmetry operations; eight unique periodic sites per conventional cell; 18 boundary-inclusive sites in one cell. Repeated blocks deduplicate shared boundaries. Links mark nearest neighbours. CC0 data; source CIF and generator included."; break
    case "V15": body = <AlgorithmIdentity/>; caption = "A mathematical construction can be checked independently of the process that discovered it. The performance metric still needs a precise definition."; method = "Published AlphaEvolve rank-48 tensor for 4×4 complex matrix multiplication; recursive Strassen baseline 49. All 4,096 entries checked from literal coefficient data without executing the downloaded notebook. Gaussian half-integer coefficients scaled by two for exact bounded arithmetic. This is an identity check, not a hardware benchmark."; break
    case "V16": body = <FeedbackComparison/>; caption = "The evaluator determines how far cheap proposal generation can carry a research programme. Different fields require different evidence."; method = "Original analytical comparison grounded in the mathematical, algorithmic, materials, protein and clinical sources in chapters 2–6. Qualitative stages, not measured durations or a universal ranking of research speed."; break
    case "V08": body = <SpatialFigure kind="zeta" fallback={<ZetaSlice/>} description="Computed magnitude landscape of the Riemann zeta function; real coordinate zero to one, imaginary coordinate ten to thirty."/>; caption = "Three familiar zeros on a finite stretch of the critical line. The 3D view opens the surrounding strip; neither view establishes the Riemann hypothesis."; method = "mpmath 1.3.0, 35 decimal digits. Grid: 41 real coordinates in [0,1] × 121 imaginary coordinates in [10,30]. Base height = log(1 + |ζ|), clipped at 1.8 and multiplied by the chosen display exaggeration. Pole s=1 lies outside this domain. The 2D slice uses 1,201 points. Three zero residuals and ζ(2)=π²/6 checked during generation. Data and generator are included with the article."; break
    case "V09": body = <ZetaBound/>; caption = "An improvement of 25.6 percentage points in the reported lower bound. It does not mean 67.2% of the Riemann hypothesis has been solved."; method = "Anthropic announcement, original paper and expert note. Rounded values follow the announcement; the note gives approximately 67.25% with a limiting error term and precise counting conventions. Full 0–100% baseline shown."; break
    case "V10": body = <SpatialFigure kind="protein" fallback={<ProteinProjection/>} description="Experimental and aligned predicted lysozyme structures, with selectable confidence, displacement and sequence colours."/>; caption = "A predicted structure and an experimental structure can be compared directly. Their agreement on a familiar protein is an illustration of the question, not an independent test of general predictive performance."; method = "Experimental PDB 1LYZ chain A residues 1–129; AlphaFold DB P00698 residues 19–147 (signal peptide excluded). All 129 residue identities verified; Cα coordinates aligned by proper-rotation least squares. Units Å. The static view colours the prediction by pLDDT; the instrument also offers aligned displacement and sequence position. Confidence is not experimental uncertainty. PDB CC0; AlphaFold CC BY 4.0. File hashes, coordinate URLs and alignment method are in protein.json."; break
    case "V11": body = <SpatialFigure kind="binding" fallback={<BindingProjection/>} description="Experimental streptavidin–biotin interface; ligand atoms and nearby protein atoms."/>; caption = "Binding has a physical geometry. Here the example is an experimentally determined streptavidin–biotin structure, chosen to explain an interface without implying an AI-generated therapeutic result."; method = "PDB 1STP chain A and BTN ligand, CC0. Violet protein atoms lie within 4 Å of a ligand atom; the threshold marks proximity, not chemical bonds or measured affinity. The displayed chain is a selected part of the deposited structure. No AI-designed molecule is represented."; break
    case "V12": body = <ProteinFunnel/>; caption = "Success must keep its denominator. A target with one successful binder and a design that binds are different units of evaluation."; method = "Anthropic’s August 2026 protein-design technical report and announcement. Totals and arm rates are reported observations, not independently replicated here. The inconclusive target and unequal experimental configurations are retained in the explanation."; break
    case "V13": body = <MeasurementAudit/>; caption = "A small analytical task can matter economically without being a new biological discovery. Agreement on one sample is evidence about that sample."; method = "Reported values from the NMR/LC-MS technical report. Purity comparison: 96.4 − 96.33 = 0.07 percentage points. No raw spectrum has been reconstructed or fabricated. The figure deliberately shows the reported measurement comparison rather than invented peaks."; break
    case "V04": body = <SpatialFigure kind="vortex" fallback={<VortexDiagram/>} description="Finite parametric vortex illustration; not a simulated Navier–Stokes solution."/>; caption = "Rotation and concentration are different geometric features. Seeing them helps frame a question; it does not establish that the fluid equations permit a singularity."; method = "Educational parametric curves, with adjustable twist, contraction and inspection plane. Defaults: angle θ = θ₀ + 7s, radius r = 2.5(1 − 0.65s), axial coordinate y = 5s − 2.5, for 0 ≤ s ≤ 1. Arbitrary units. This drawing is not a velocity field or a numerical solution; it makes no claim about viscosity or finite-time blowup."; break
    case "V05": body = <VerificationTimeline/>; caption = "An announcement, a proof artefact, independent scrutiny and a prize decision answer different questions."; method = "Sources: OpenAI announcement and repository; Clay prize rules. Evidence cut-off 9 September 2026. Unresolved means not established by the evidence assembled for this essay, not that the claim is false."; break
    case "V06": body = <FermatTimeline/>; caption = "The historical proof and its later formalisation belong on different tracks. Both depend on contributions that extend beyond one person or company."; method = "Wiles, Annals of Mathematics (1995); Anthropic announcement (4 September 2026); repository attribution. Timeline is schematic and does not encode elapsed time by distance."; break
    case "V07": body = <ProofDependencies/>; caption = "A small real slice is more informative than a decorative cloud of thousands of theorems. The final statement depends on explicitly named intermediate work."; method = "Transcribed relationships from the released PROOF-PATH.md, inspected 9 September 2026. The entire repository was not rebuilt here. The upstream source is linked directly; only this bounded slice is shown."; break
    case "V01": body = <SpatialFigure kind="atlas" fallback={<Atlas />} description="A schematic research atlas with four layers: questions, attempts, checked results and useful changes."/>; caption = "The opening question is who gets to enter this process. A wider field of attempts only becomes progress when checking and implementation can absorb it."; method = "Original schematic. Node counts, distances and connections are explanatory, not measurements. In 3D, the four planes represent the four named stages. The highlighted path carries the same meaning in both views."; break
    case "V02": body = <Capability/>; caption = "An advanced result and worldwide access to the system that produced it are different facts. This distinction sets the standard for the essay’s premise."; method = "Dated 9 September 2026. Based on the OpenAI Navier–Stokes announcement and Anthropic’s Fermat, zeta, protein-design and science-access announcements. No inference that a public product shares an internal configuration’s capabilities."; break
    case "V03": body = <TaskProfile/>; caption = "PhD-level intelligence is useful shorthand only if we name the work. There is no universal score here: each research activity has a different test of competence."; method = "Original analytical decomposition of research work. This is not a benchmark or a ranking of models against human researchers."; break
    default: throw new Error(`Figure ${id} has not been built`)
  }
  return <figure className="iwp-figure" id={`figure-${id}`}><header className="iwp-figure-header"><div><p className="iwp-figure-kicker">Figure {id.slice(1)} / {metadata.dimension}</p><h3>{metadata.title}</h3></div><span className="iwp-figure-kind">{metadata.evidence_kind}</span></header><div className="iwp-figure-body" tabIndex={0} aria-label={`${metadata.title}. Wide diagrams can be scrolled horizontally on small screens.`}>{body}</div><figcaption><p>{caption}</p><details><summary>Method &amp; evidence</summary><p>{method}</p></details></figcaption></figure>
}
