"use client"

import { useState } from "react"

const dependencies=[
  {name:"Models",question:"Can the research continue with another provider?",asset:"Versioned artefacts, evaluations and usable alternatives",source:"#source-S47"},
  {name:"Compute",question:"Can the lab obtain capacity it can afford and use?",asset:"Commercial, shared and public access routes",source:"#source-S59"},
  {name:"Data",question:"Can another researcher inspect the relevant evidence?",asset:"Usable records, provenance and appropriate access",source:"#source-S46"},
  {name:"Experiments",question:"Can the proposal receive an independent physical test?",asset:"Facilities, samples, calibration and skilled operators",source:"#chapter-12"},
  {name:"Customers",question:"Can a small supplier demonstrate a useful contribution?",asset:"Clear acceptance criteria and workable procurement",source:"#chapter-10"},
]
export function DependencyNetwork() {
  const [index,setIndex]=useState(0), selected=dependencies[index]
  return <><div className="iwp-controls">{dependencies.map((d,i)=><button key={d.name} type="button" aria-pressed={index===i} onClick={()=>setIndex(i)}>{d.name}</button>)}</div><svg viewBox="0 0 1000 360" role="img" aria-label={`A small lab depends on models, compute, data, experiments and customers. Selected dependency: ${selected.name}. ${selected.question}`}><circle cx="500" cy="185" r="64" fill="#182c40" stroke="#e7b778"/><text x="500" y="182" textAnchor="middle" className="iwp-svg-title">Small lab</text><text x="500" y="205" textAnchor="middle">Effective agency</text>{dependencies.map((d,i)=>{const angle=i*Math.PI*2/5-Math.PI/2,x=500+350*Math.cos(angle),y=185+140*Math.sin(angle);return <g key={d.name}><path d={`M500 185L${x} ${y}`} stroke={i===index?"#e7b778":"#314050"} strokeWidth={i===index?2:1}/><rect x={x-72} y={y-24} width="144" height="48" rx="24" fill="#14263a" stroke={i===index?"#e7b778":"#7ed1d2"}/><text x={x} y={y+5} textAnchor="middle" style={{fill:i===index?"#e7b778":"#f2e9d6"}}>{d.name}</text></g>})}<circle cx="500" cy="185" r="64" fill="#182c40" stroke="#e7b778"/><text x="500" y="182" textAnchor="middle" className="iwp-svg-title">Small lab</text><text x="500" y="205" textAnchor="middle">Effective agency</text></svg><div className="iwp-notice" aria-live="polite"><strong>{selected.question}</strong><p>{selected.asset}. <a href={selected.source}>Follow the evidence or analysis →</a></p></div></>
}

export function AccessFutures() {
  const [open,setOpen]=useState(true)
  return <><div className="iwp-controls"><button type="button" aria-pressed={open} onClick={()=>setOpen(true)}>Several workable routes</button><button type="button" aria-pressed={!open} onClick={()=>setOpen(false)}>Concentrated control</button></div><svg viewBox="0 0 1000 315" role="img" aria-label={open?"Conditional open-access scenario: several research groups can reach multiple independent sources of compute, evidence and deployment.":"Conditional concentrated scenario: many research groups depend on a single bundle controlling compute, evidence and deployment."}>{Array.from({length:7},(_,i)=><g key={i}><circle cx="125" cy={45+i*36} r="8" fill="#7ed1d2"/>{(open?[0,1,2]:[1]).map(j=><path key={j} d={`M140 ${45+i*36}C330 ${45+i*36} 330 ${65+j*90} 500 ${65+j*90}`} fill="none" stroke={open?"#7ed1d2":"#b6a1e4"} opacity=".3"/>)}</g>)}{(open?[0,1,2]:[1]).map(j=><g key={j}><rect x="500" y={35+j*90} width="250" height="60" rx="8" fill="#14263a" stroke={open?"#7ed1d2":"#e7b778"}/><text x="625" y={72+j*90} textAnchor="middle">{open?["Alternative providers","Shared facilities","Independent evaluation"][j]:"One controlling bundle"}</text><path d={`M750 ${65+j*90}H880`} stroke="#e7b778"/><circle cx="890" cy={65+j*90} r="10" fill="#e7b778"/></g>)}<text x="125" y="307" textAnchor="middle">More people can attempt research</text></svg><div className="iwp-notice" aria-live="polite">{open?"Assumptions: useful alternatives, portable work, accessible tests and buyers willing to evaluate new contributors. Possible effect: wider bargaining power and participation.":"Assumptions: capable proposal generation is widespread, but decisive resources and routes to customers are bundled under few owners. Possible effect: more participation with continuing dependence."} Neither scenario has an assigned probability.</div></>
}

const actions=[
  {name:"University",rows:[["Open a route to a bounded test","Time to decision; eligible outside contributors","Continue if evidence quality holds while access improves"],["Assess judgement directly","Explanation, transfer and detection of errors","Revise assessment when polished output hides weak understanding"],["Fund shared research memory","Reusable data, negative results and maintained tools","Support contributions that other teams can actually use"]]},
  {name:"Enterprise R&D",rows:[["Compare one real workflow","Checked outcomes, total effort, rework and elapsed time","Expand only when the complete process improves"],["Give handoffs a decision owner","Waiting time and reasons for delay","Remove delays that add no useful evidence"],["Evaluate a small outside supplier","Independent tests and customer benefit","Buy a useful contribution regardless of team size"]]},
  {name:"Small lab",rows:[["Make one bounded promise","A reproducible result on an independent test","Narrow or stop a claim that fails its own criterion"],["Budget the whole experiment","Compute, review, facilities and failed attempts","Scale only where more attempts add useful information"],["Preserve alternatives","Portable artefacts and realistic substitute providers","Address a dependency before it becomes an existential risk"]]},
  {name:"Public funder",rows:[["Finance the missing test","Additional credible work enabled","Target the constraint rather than the most visible tool"],["Make access decisions inspectable","Who applies, succeeds and cannot proceed","Change rules that exclude without improving the evidence"],["Pay for independent checking","Replication, corrections and reusable records","Reward reliable knowledge, including useful negative results"]]},
]
export function InstitutionActions() {
  const [index,setIndex]=useState(0), selected=actions[index]
  return <><div className="iwp-controls">{actions.map((a,i)=><button key={a.name} type="button" aria-pressed={index===i} onClick={()=>setIndex(i)}>{a.name}</button>)}</div><div className="iwp-action-cards" aria-live="polite">{selected.rows.map(([action,measure,decision],i)=><article key={action}><span className="iwp-card-number">0{i+1}</span><h4>{action}</h4><p><strong>Measure</strong>{measure}</p><p><strong>Decide</strong>{decision}</p></article>)}</div><p className="iwp-notice">These are proposed operating choices, not measured effects. Choose a scope and baseline before the trial; preserve evidence that could justify stopping it.</p></>
}

const paths=[
  {field:"Mathematics",question:"A precisely stated claim",attempt:"Candidate proof and formal artefact",check:"Statement, assumptions and independent scrutiny",use:"Knowledge that others can inspect and extend",anchor:"#chapter-02"},
  {field:"Biology",question:"A testable biological hypothesis",attempt:"A candidate and a reproducible protocol",check:"Appropriate measurements and replication",use:"A justified next experiment; clinical benefit needs further evidence",anchor:"#chapter-05"},
  {field:"Industry",question:"A problem someone needs solved",attempt:"A bounded design or operating proposal",check:"Relevant tests and accountable deployment",use:"A measurable improvement for a customer or community",anchor:"#chapter-12"},
]
export function ClosingPaths() {
  const [index,setIndex]=useState(0), p=paths[index]
  return <><div className="iwp-controls">{paths.map((path,i)=><button key={path.field} type="button" aria-pressed={i===index} onClick={()=>setIndex(i)}>{path.field}</button>)}</div><div className="iwp-closing-path" aria-live="polite">{[["Ask",p.question],["Attempt",p.attempt],["Check",p.check],["Use",p.use]].map(([label,detail],i)=><div key={label}><span>{String(i+1).padStart(2,"0")}</span><h4>{label}</h4><p>{detail}</p></div>)}</div><p className="iwp-closing-statement">The opportunity is a wider right to try.<br/><em>The achievement is a result that survives.</em></p><a className="iwp-path-link" href={p.anchor}>Return to the {p.field.toLowerCase()} evidence →</a></>
}
