"use client"

import { useState } from "react"
import { SpatialFigure } from "./SpatialFigure"
import { reservoirHeight } from "@/lib/synaptic/intelligence-without-permission/geometry"
import { pipelineScenario } from "@/lib/synaptic/intelligence-without-permission/scenarios"

export function ReservoirStudy() {
  const alternative=0
  const colors=["#e7b778","#7ed1d2","#b6a1e4","#526476"]
  const fallback=<svg viewBox="0 0 1000 425" role="img" aria-label={`Synthetic reservoir interpretation ${alternative===0?"A":"B"}. Four illustrative subsurface boundaries and a vertical measurement line. No actual field, reserves or production prediction.`}>{[0,1,2,3].map(layer=>{const points=Array.from({length:101},(_,i)=>[60+i*8.8,105-reservoirHeight(i*.08-4,0,layer,alternative)*55]);return <g key={layer}><path d={`M${points.map(p=>p.map(v=>Number(v.toFixed(3))).join(",")).join("L")}L940,390L60,390Z`} fill={colors[layer]} fillOpacity=".15"/><path d={`M${points.map(p=>p.map(v=>Number(v.toFixed(3))).join(",")).join("L")}`} fill="none" stroke={colors[layer]} strokeWidth="2"/></g>})}<path d="M340 24V365" stroke="#f2e9d6" strokeWidth="3" strokeDasharray="6 6"/><text x="360" y="36">A limited observation location</text><text x="70" y="355">Interpretations can differ between observations.</text><text x="70" y="410">Cross-section z = 0 · arbitrary units · no flow simulation</text></svg>
  return <SpatialFigure kind="reservoir" fallback={fallback} description="Synthetic sedimentary block with a movable geological cutaway, well and linked depth section."/>

}

const sectors=[
  {name:"Oil and gas",constraint:"Incomplete observations across assets and operating conditions",capability:"Compare mechanisms, interpret measurements, plan tests",entry:"Specialised diagnosis, monitoring or maintenance research",response:"Connect records, facilities and rapid bounded trials",benefit:"Less avoidable downtime and better emissions response",remaining:"Field access, rare failures and accountable intervention",measure:"Verified fault detection, repair time, false alarms, measured emissions"},
  {name:"Pharma and biotech",constraint:"Many candidates; expensive evidence about biology",capability:"Better hypotheses, design proposals and analytical work",entry:"A narrow assay, target or experimental service",response:"Improve experimental selection and independent replication",benefit:"More informative research; useful treatments if clinical evidence follows",remaining:"Biological validity, trials, manufacture and access",measure:"Reproducible results, informative failures, clinical outcomes where applicable"},
  {name:"Manufacturing and design",constraint:"Interacting requirements and costly physical iteration",capability:"Explore alternatives and carry forward reasons for failure",entry:"A component, process improvement or specialised product",response:"Use test facilities to evaluate a broader set of proposals",benefit:"More reliable products, less scrap and better repairability",remaining:"Materials, tolerances, suppliers and qualification",measure:"Yield, field reliability, rework, total product cost"},
  {name:"Energy and utilities",constraint:"Complex networks, incomplete sensing and slow deployment",capability:"Forecast, diagnose and compare operating or investment choices",entry:"Planning, asset diagnosis or data-quality services",response:"Validate in shadow mode before bounded operational use",benefit:"More reliable supply and better use of existing equipment",remaining:"Physical network limits, resilience and operating responsibility",measure:"Service reliability, measured losses, validated capacity, operator workload"},
  {name:"Software and services",constraint:"Unclear requirements, integration and maintenance",capability:"Build, test and explain bounded changes",entry:"A specialised workflow with transparent acceptance criteria",response:"Price and manage useful outcomes rather than generated output",benefit:"Affordable tools for neglected needs and better maintained systems",remaining:"Correctness, customer context, security and support",measure:"Accepted changes, defects, rework, elapsed time and total cost"},
]
export function IndustryComparison() {
  const [index,setIndex]=useState(0), sector=sectors[index]
  const labels={constraint:"Present constraint",capability:"Relevant capability",entry:"Challenger entry",response:"Incumbent response",benefit:"Potential benefit",remaining:"What remains difficult",measure:"Evidence of progress"}
  return <><div className="iwp-controls">{sectors.map((s,i)=><button type="button" key={s.name} aria-pressed={index===i} onClick={()=>setIndex(i)}>{s.name}</button>)}</div><div aria-live="polite"><h4>{sector.name}</h4><dl className="iwp-fact-grid">{Object.entries(labels).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{sector[key as keyof typeof sector]}</dd></div>)}</dl></div><details><summary>Compare all five sectors</summary><div className="iwp-table-scroll"><table className="iwp-table"><thead><tr><th scope="col">Sector</th><th scope="col">Possible entry</th><th scope="col">Potential benefit</th><th scope="col">Remaining constraint</th></tr></thead><tbody>{sectors.map(s=><tr key={s.name}><td>{s.name}</td><td>{s.entry}</td><td>{s.benefit}</td><td>{s.remaining}</td></tr>)}</tbody></table></div></details></>
}

export function PipelineCapacity() {
  const [arrivals,setArrivals]=useState(100),[validation,setValidation]=useState(30),[deployment,setDeployment]=useState(10)
  const r=pipelineScenario(arrivals,validation,deployment)
  const controls=[{label:"Candidate arrivals",value:arrivals,set:setArrivals},{label:"Validation capacity",value:validation,set:setValidation},{label:"Deployment capacity",value:deployment,set:setDeployment}]
  return <><div className="iwp-controls">{controls.map(c=><label key={c.label}>{c.label}: <strong>{c.value}/period</strong><input type="range" min="0" max="200" step="5" value={c.value} onChange={e=>c.set(Number(e.target.value))}/></label>)}</div><svg viewBox="0 0 1000 320" role="img" aria-label={`${arrivals} arrivals, ${r.validated} validated and ${r.deployed} deployed in one illustrative period. ${r.awaitingValidation} await validation and ${r.awaitingDeployment} await deployment.`}>{[["Arrive",arrivals,"#7ed1d2"],["Validated",r.validated,"#b6a1e4"],["Deployed",r.deployed,"#e7b778"]].map(([name,value,color],i)=><g key={name}><text x="30" y={60+i*83}>{name}</text><rect x="175" y={32+i*83} width="730" height="38" fill="#1d2b3b"/><rect x="175" y={32+i*83} width={Number(value)*3.65} height="38" fill={String(color)}/><text x="930" y={58+i*83}>{value}</text></g>)}<text x="175" y="300">0</text><text x="905" y="300" textAnchor="end">200 candidates / period</text></svg><p className="iwp-notice" aria-live="polite">Waiting for validation: <strong>{r.awaitingValidation}</strong>. Waiting for deployment: <strong>{r.awaitingDeployment}</strong>. This capacity-only illustration starts with empty queues and assumes every processed candidate passes. Real rejection, rework and resource conflicts are omitted.</p></>
}
