"use client"

import { useState } from "react"
import { elapsedTimeScenario, savingsScenario } from "@/lib/synaptic/intelligence-without-permission/scenarios"

export function RemainingClocks() {
  const [share,setShare]=useState(50),[speed,setSpeed]=useState(10), r=elapsedTimeScenario(share/100,speed)
  return <><div className="iwp-control-grid"><div className="iwp-slider"><label htmlFor="iwp-time-share">Share of serial time accelerated <output>{share}%</output></label><input id="iwp-time-share" type="range" min="10" max="90" value={share} onChange={e=>setShare(Number(e.target.value))}/></div><div className="iwp-slider"><label htmlFor="iwp-time-speed">Speedup of that stage <output>{speed}×</output></label><input id="iwp-time-speed" type="range" min="1" max="100" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></div></div><svg viewBox="0 0 1000 295" role="img" aria-label={`A 100-unit serial project becomes ${r.total.toFixed(1)} units: ${r.unchanged.toFixed(1)} unchanged and ${r.accelerated.toFixed(1)} accelerated. The theoretical lower limit is ${r.unchanged.toFixed(1)} units.`}><text x="20" y="70">Before</text><rect x="150" y="45" width={(100-share)*7.5} height="46" fill="#526476"/><rect x={150+(100-share)*7.5} y="45" width={share*7.5} height="46" fill="#7ed1d2"/><text x="935" y="74">100</text><text x="20" y="155">After</text><rect x="150" y="130" width={r.unchanged*7.5} height="46" fill="#526476"/><rect x={150+r.unchanged*7.5} y="130" width={r.accelerated*7.5} height="46" fill="#e7b778"/><text x={170+r.total*7.5} y="160">{r.total.toFixed(1)}</text><line x1={150+r.unchanged*7.5} x2={150+r.unchanged*7.5} y1="30" y2="215" stroke="#b6a1e4" strokeDasharray="4 6"/><text x="150" y="245">Grey: unchanged stage</text><text x="490" y="245">Teal / gold: accelerated stage</text><text x="150" y="280">Arbitrary elapsed-time units · serial stages · no queue or overlap</text></svg><div className="iwp-metrics" aria-live="polite"><div><strong>{r.total.toFixed(1)}</strong><span>new total, from 100 units</span></div><div><strong>{r.overallSpeedup.toFixed(2)}×</strong><span>whole-project speedup</span></div><div><strong>{r.unchanged.toFixed(0)}</strong><span>limit if analysis were instantaneous</span></div></div></>
}

export function SavingsDistribution() {
  const [share,setShare]=useState(25),[reduction,setReduction]=useState(50),[pass,setPass]=useState(50),r=savingsScenario(share/100,reduction/100,pass/100)
  const inputs=[{id:"share",label:"Research share of cost",v:share,set:setShare},{id:"reduction",label:"Reduction in that cost",v:reduction,set:setReduction},{id:"pass",label:"Savings passed to customer",v:pass,set:setPass}]
  return <><div className="iwp-control-grid">{inputs.map(c=><div className="iwp-slider" key={c.id}><label htmlFor={`iwp-saving-${c.id}`}>{c.label}<output>{c.v}%</output></label><input id={`iwp-saving-${c.id}`} type="range" min="0" max="100" value={c.v} onChange={e=>c.set(Number(e.target.value))}/></div>)}</div><svg viewBox="0 0 1000 290" role="img" aria-label={`Illustrative price falls from 100 to ${r.newPrice.toFixed(1)}. Cost falls from 80 to ${r.newCost.toFixed(1)}. Unit margin becomes ${r.newMargin.toFixed(1)}. Customer savings are ${r.customerSaving.toFixed(1)}.`}>{[[80,20,0,"Baseline"],[r.newCost,r.newMargin,r.customerSaving,"Scenario"]].map(([cost,margin,customer,label],i)=><g key={label}><text x="20" y={76+i*95}>{label}</text><rect x="150" y={45+i*95} width={Number(cost)*7.5} height="48" fill="#526476"/><rect x={150+Number(cost)*7.5} y={45+i*95} width={Number(margin)*7.5} height="48" fill="#e7b778"/><rect x={150+(Number(cost)+Number(margin))*7.5} y={45+i*95} width={Number(customer)*7.5} height="48" fill="#7ed1d2"/></g>)}<text x="150" y="235">Grey: cost</text><text x="390" y="235">Gold: unit margin</text><text x="680" y="235">Teal: customer saving</text><text x="150" y="280">Each bar reconciles to the original price of 100 · abstract currency units</text></svg><div className="iwp-metrics" aria-live="polite"><div><strong>{r.newPrice.toFixed(1)}</strong><span>new price · baseline 100</span></div><div><strong>{r.newCost.toFixed(1)}</strong><span>new cost · baseline 80</span></div><div><strong>{r.newMargin.toFixed(1)}</strong><span>unit margin · baseline 20</span></div></div><p className="iwp-notice">Fixed sales volume and quality; no new deployment costs, taxes, capital costs, demand response or competitor behaviour. Margin means price minus the modelled unit cost, not a company’s net profit.</p></>
}

export function MarketTiming() {
  const [fast,setFast]=useState(true)
  const steps=fast?["Result can be independently tested","Fits an existing operating process","Buyer can compare alternatives","Competition reaches price or quality"]:["Result requires new physical evidence","Facilities or integration need investment","Customers wait for qualification","Commercial effects arrive unevenly"]
  return <><div className="iwp-controls"><button type="button" aria-pressed={fast} onClick={()=>setFast(true)}>Fewer adoption barriers</button><button type="button" aria-pressed={!fast} onClick={()=>setFast(false)}>More adoption barriers</button></div><svg viewBox="0 0 1000 360" role="img" aria-label={`Conditional sequence, not a dated forecast: ${steps.join("; ")}.`}><path d="M70 60V290" stroke="#7ed1d2"/>{steps.map((step,i)=><g key={step}><circle cx="70" cy={60+i*75} r="15" fill="#14263a" stroke={i===3?"#e7b778":"#7ed1d2"}/><text x="70" y={65+i*75} textAnchor="middle">{i+1}</text><text x="110" y={66+i*75} className="iwp-svg-title">{step}</text><line x1="110" x2="940" y1={92+i*75} y2={92+i*75} stroke="#314050"/></g>)}</svg><p className="iwp-notice">An announcement can change expectations before operating results change. The diagram gives conditions and sequence; spacing does not represent duration or the probability of displacement.</p></>
}
