"use client"
import { useEffect, useId, useMemo, useRef, useState, type ReactNode } from 'react'
import { flushSync } from 'react-dom'
import Image from 'next/image'
import previewRevisions from '@/lib/synaptic/intelligence-without-permission/preview-revisions.json'
import { analyse, formatControl, instruments, loadInstrumentData, sanitizeSettings, type ScienceData, type Settings, type SceneKind } from '@/lib/synaptic/intelligence-without-permission/instruments'
import { InstrumentViewport, type ViewportCommand } from './InstrumentViewport'
import { InstrumentPlot } from './InstrumentPlot'
export type { SceneKind } from '@/lib/synaptic/intelligence-without-permission/instruments'

export function SpatialFigure({kind,fallback,description}:{kind:SceneKind;fallback:ReactNode;description:string}){
 const config=instruments[kind],id=useId(),root=useRef<HTMLDivElement>(null),command=useRef<((action:ViewportCommand,value?:number)=>void)|null>(null)
 const [settings,setSettings]=useState<Settings>(()=>({...config.defaults})),[active,setActive]=useState(false),[data,setData]=useState<ScienceData|null>(null),[failure,setFailure]=useState(false),[zoom,setZoom]=useState(100),[ready,setReady]=useState(false),[expanded,setExpanded]=useState(false),[preset,setPreset]=useState<number|null>(null),[baseline,setBaseline]=useState<Settings|null>(null),[labels,setLabels]=useState(true),[quality,setQuality]=useState(true),[status,setStatus]=useState(''),[shareURL,setShareURL]=useState(''),[preview,setPreview]=useState(true),[staticOpen,setStaticOpen]=useState(false)
 const analysis=useMemo(()=>analyse(kind,settings,data||{}),[kind,settings,data]),comparison=useMemo(()=>baseline?analyse(kind,baseline,data||{}):null,[kind,baseline,data])
 const spectrum=kind==='vortex'?{label:settings.color?'Colour / filament family':'Colour / axial position',min:'Start',max:'End'}:kind==='zeta'?{label:'Colour / log(1 + |ζ|)',min:'0',max:'1.8'}:kind==='protein'&&settings.color?{label:settings.color===2?'Prediction colour / sequence':'Prediction colour / displacement',min:settings.color===2?'Residue 1':'0 Å',max:settings.color===2?'Residue 129':'≥1.85 Å'}:kind==='metrology'?{label:'Colour / displacement magnitude',min:'0 a.u.',max:'≥5 a.u.'}:null
 const legend=kind==='protein'?(settings.color?['Cyan · experiment','Spectrum · prediction','White · selected Cα']:['Cyan · experiment / pLDDT ≥90','Gold · pLDDT 70–89','Violet · pLDDT <70']):kind==='crystal'&&!settings.color?['Gold · carbon sites','Cyan · nearest neighbours','Fine lines · cell boundaries']:config.legend
 function activate(){setFailure(false);window.dispatchEvent(new CustomEvent('iwp:spatial-selected',{detail:id}));setActive(true)}
 function change(key:string,value:number){setSettings(previous=>({...previous,[key]:value}));setPreset(null);activate()}
 function applyPreset(index:number){setSettings({...config.defaults,...config.presets[index].settings});setPreset(index);activate()}
 useEffect(()=>{const select=(event:Event)=>{if((event as CustomEvent<string>).detail!==id){setActive(false);setExpanded(false)}};window.addEventListener('iwp:spatial-selected',select);return()=>window.removeEventListener('iwp:spatial-selected',select)},[id])
 useEffect(()=>{const open=(event:Event)=>{if((event as CustomEvent<string>).detail===kind){setFailure(false);window.dispatchEvent(new CustomEvent('iwp:spatial-selected',{detail:id}));setActive(true)}};window.addEventListener('iwp:open-instrument',open);return()=>window.removeEventListener('iwp:open-instrument',open)},[id,kind])
 useEffect(()=>{let wasOpen=false;const before=()=>{wasOpen=Boolean(root.current?.querySelector<HTMLDetailsElement>('.iwp-instrument-static')?.open);flushSync(()=>setStaticOpen(true))};const after=()=>setStaticOpen(wasOpen);window.addEventListener('beforeprint',before);window.addEventListener('afterprint',after);return()=>{window.removeEventListener('beforeprint',before);window.removeEventListener('afterprint',after)}},[])
 useEffect(()=>{let cancelled=false;const load=()=>{void loadInstrumentData(kind).then(result=>{if(!cancelled)setData(result)}).catch(()=>{if(!cancelled)setFailure(true)})};const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){load();observer.disconnect()}},{rootMargin:'700px'});if(root.current)observer.observe(root.current);return()=>{cancelled=true;observer.disconnect()}},[kind])
 useEffect(()=>{if(!active)return;let cancelled=false;setReady(false);setLabels(true);setQuality(true);void loadInstrumentData(kind).then(result=>{if(!cancelled)setData(result)}).catch(()=>{if(!cancelled){setFailure(true);setActive(false)}});return()=>{cancelled=true}},[active,kind])
 useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get('instrument')!==kind)return;try{const restored=sanitizeSettings(kind,JSON.parse(params.get('settings')||'{}'));setSettings(restored);window.dispatchEvent(new CustomEvent('iwp:spatial-selected',{detail:id}));setActive(true);root.current?.scrollIntoView({block:'start'})}catch{/* An invalid shared state leaves the documented defaults intact. */}},[kind,id])
 useEffect(()=>{if(!expanded)return;const previous=document.activeElement as HTMLElement|null,oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';root.current?.focus();const keys=(e:KeyboardEvent)=>{if(e.key==='Escape'){setExpanded(false);return}if(e.key==='Tab'){const targets=root.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),summary,[tabindex="0"]');if(!targets?.length)return;const first=targets[0],last=targets[targets.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===root.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',keys);return()=>{document.body.style.overflow=oldOverflow;document.removeEventListener('keydown',keys);previous?.focus()}},[expanded])
 function downloadState(){const content={title:config.title,article:'Intelligence Without Permission',author:'Tarry Singh',version:2,instrument:kind,settings,baseline,readings:analysis.readings,method:config.method,source:config.source||'Original illustrative model',dataFile:config.source?new URL(config.source,window.location.origin).href:null},url=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`synaptic-${kind}-settings.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Settings, readouts and method saved.')}
 async function share(){const url=new URL(window.location.href);url.searchParams.set('instrument',kind);url.searchParams.set('settings',JSON.stringify(settings));url.hash=root.current?.closest('figure')?.id||'';try{await navigator.clipboard.writeText(url.href);setStatus('Link copied. It restores these instrument settings.');setShareURL('')}catch{setShareURL(url.href);setStatus('Copy the link below to share these settings.')}}
 const pick=(value:number)=>{if(kind==='protein')change('residue',value);if(kind==='binding')change('atom',value)}
 const plotSelect=kind==='protein'?(i:number)=>change('residue',i+1):kind==='binding'?(i:number)=>change('atom',i+1):kind==='vortex'?(i:number)=>change('slice',i/80):kind==='agents'?(i:number)=>change('population',1+i/10):kind==='reservoir'?(i:number)=>change('well',Math.max(-3.5,Math.min(3.5,-4+i/20))):undefined
 return <div ref={root} className={`iwp-instrument ${expanded?'iwp-instrument-expanded':''}`} data-instrument={kind} tabIndex={expanded?-1:undefined} role={expanded?'dialog':undefined} aria-modal={expanded||undefined} aria-label={`${config.title} research instrument`}>
  <div className="iwp-instrument-bar"><span className="iwp-instrument-brand"><i/>{active?'Interactive laboratory':'Open laboratory'} <b>/</b> {config.evidence}</span><div><button type="button" onClick={()=>{if(active){setActive(false);setReady(false)}else activate()}} aria-pressed={active}>{active?'Pause 3D':'Launch 3D'} <span aria-hidden="true">{active?'Ⅱ':'↗'}</span></button><button type="button" onClick={()=>{setExpanded(!expanded);if(!active)activate()}} aria-label={expanded?'Close expanded instrument':'Expand instrument'}>{expanded?'Close ×':'Expand ⤢'}</button></div></div>
  <div className="iwp-instrument-intro"><div><span className="iwp-micro">Experiment with the argument</span><h4>{config.title}</h4><p>{config.question}</p></div><span className="iwp-instrument-number">{String(Object.keys(instruments).indexOf(kind)+1).padStart(2,'0')}<small>/ 10</small></span></div>
  <div className="iwp-laboratory-grid"><div className="iwp-laboratory-main"><div className="iwp-scene-stage">
   {active&&data?<InstrumentViewport kind={kind} settings={settings} data={data} onPick={pick} onZoom={setZoom} onReady={()=>setReady(true)} onError={()=>{setFailure(true);setActive(false);setReady(false)}} commandRef={command}/>:<div className="iwp-instrument-preview">{preview?<Image src={`/synaptic/intelligence-without-permission/previews/${kind}.webp?v=${previewRevisions[kind]}`} alt={description} fill sizes="(min-width: 1100px) 850px, 100vw" onError={()=>setPreview(false)}/>:<div className="iwp-preview-fallback">{fallback}</div>}<button type="button" className="iwp-launch-overlay" onClick={activate}><span aria-hidden="true">◇</span>Enter the 3D study <small>Adjust · inspect · compare</small></button></div>}
   {active&&!data&&<div className="iwp-instrument-loading" role="status">Loading the source data…</div>}
   <div className="iwp-scene-corner"><span>{active&&ready?'LIVE VIEW':'DEFAULT VIEW'}</span><span>{config.evidence}</span></div>
   {active&&ready&&<div className="iwp-scene-navigation" aria-label="Camera controls">{([['isometric','3D'],['front','Front'],['top','Top'],['left','↶'],['right','↷'],['closer','＋'],['further','−']] as [ViewportCommand,string][]).map(([action,label])=><button type="button" key={action} onClick={()=>command.current?.(action)} aria-label={{isometric:'Isometric view',front:'Front view',top:'Top view',left:'Rotate left',right:'Rotate right',closer:'Zoom in',further:'Zoom out',export:'Export',labels:'Labels',quality:'Quality',zoom:'Set magnification'}[action]}>{label}</button>)}</div>}
  </div><div className="iwp-instrument-legend">{legend.map(text=><span key={text}><i style={{background:text.startsWith('Spectrum')?'linear-gradient(90deg,#643dc9,#21c6ce,#f56d49)':text.startsWith('Cyan')?'#35c9ec':text.startsWith('Violet')?'#b97bf1':text.startsWith('White')||text.startsWith('Selected')?'#eaf5ff':text.startsWith('Copper')?'#e39b61':text.startsWith('Blue')?'#83adff':text.startsWith('Surface')?'#4c99a9':text.startsWith('Fine')?'#54778b':'#ffb64f'}}/>{text}</span>)}</div>
  {failure&&<p className="iwp-instrument-warning" role="status">The 3D view could not load. The 2D explanation and source data remain available. Try Launch 3D again to retry.</p>}
  {analysis.series.length>0&&<InstrumentPlot analysis={analysis} onSelect={plotSelect}/>}
  {spectrum&&<div className="iwp-spectrum"><span>{spectrum.label}</span><div><small>{spectrum.min}</small><i/><small>{spectrum.max}</small></div></div>}
  {!analysis.series.length&&<div className="iwp-obligation-grid">{(kind==='motor'?['Clearances / fit','Heat / insulation','Vibration / noise','Manufacturing / life']:['Access / tools','Proposal / method','Check / evidence','Deployment / responsibility']).map((text,i)=><div key={text}><span>0{i+1}</span><strong>{text.split(' / ')[0]}</strong><small>{text.split(' / ')[1]}</small></div>)}</div>}
  </div><aside className="iwp-instrument-panel" aria-label={`${config.title} controls`}>
   <div className="iwp-panel-title"><span>Controls</span><button type="button" onClick={()=>{setSettings({...config.defaults});setPreset(null);setBaseline(null);setStatus('Default settings and camera restored.');command.current?.('isometric');activate()}}>Reset</button></div>
   {config.controls.map(c=><div className="iwp-instrument-control" key={c.key}><label htmlFor={`${id}-${c.key}`}>{c.label}<output>{formatControl(c,settings)}</output></label>{c.options?<select id={`${id}-${c.key}`} value={settings[c.key]} onChange={e=>change(c.key,Number(e.target.value))}>{c.options.map((option,i)=><option key={option} value={i}>{option}</option>)}</select>:<><input id={`${id}-${c.key}`} type="range" min={c.min} max={c.max} step={c.step} value={settings[c.key]} onChange={e=>change(c.key,Number(e.target.value))}/><div className="iwp-range-extents"><span>{formatControl(c,{...settings,[c.key]:c.min})}</span><span>{formatControl(c,{...settings,[c.key]:c.max})}</span></div></>}</div>)}
   <div className="iwp-guided"><span className="iwp-micro">Three ways in</span>{config.presets.map((p,i)=><button type="button" key={p.label} aria-pressed={preset===i} onClick={()=>applyPreset(i)}><span>0{i+1}</span>{p.label}<b>↗</b></button>)}</div>
   <div className="iwp-zoom-panel"><label htmlFor={`${id}-zoom`}>Magnification<output>{zoom}%</output></label><div><button type="button" aria-label="Decrease magnification" disabled={!ready||!active} onClick={()=>command.current?.('further')}>−</button><input id={`${id}-zoom`} type="range" min="50" max="200" step="1" value={zoom} disabled={!ready||!active} onChange={e=>command.current?.('zoom',Number(e.target.value))}/><button type="button" aria-label="Increase magnification" disabled={!ready||!active} onClick={()=>command.current?.('closer')}>+</button></div><small>Scroll or pinch to zoom</small></div><div className="iwp-instrument-display"><button type="button" disabled={!ready||!active} aria-pressed={labels} onClick={()=>{setLabels(!labels);command.current?.('labels')}}>Labels</button><button type="button" disabled={!ready||!active} aria-pressed={quality} onClick={()=>{setQuality(!quality);command.current?.('quality')}}>Studio light</button></div>
  </aside></div>
  <div className="iwp-instrument-readings" aria-live="polite">{analysis.readings.length?analysis.readings.map((r,i)=><div key={r.label}><span>{r.label}</span><strong>{r.value}<small>{r.unit}</small></strong>{comparison?.readings[i]&&<em>Saved: {comparison.readings[i].value} {comparison.readings[i].unit}</em>}</div>):<p>Source measurements load as this instrument enters view.</p>}</div>
  <div className="iwp-instrument-insight"><span>Observe</span><p>{preset!==null?config.presets[preset].note:analysis.insight}</p></div>
  <div className="iwp-instrument-actions"><div><button type="button" aria-pressed={!!baseline} onClick={()=>{setBaseline(baseline?null:{...settings});setStatus(baseline?'Saved comparison cleared.':'Readouts saved. Adjust the controls to compare.')}}>{baseline?'Clear comparison':'Pin a comparison'}</button><button type="button" onClick={share}>Share this view ↗</button></div><div><button type="button" onClick={downloadState}>Settings ↓</button><button type="button" disabled={!active||!ready} onClick={()=>command.current?.('export')}>Image ↓</button></div></div>
  {status&&<p className="iwp-instrument-status" role="status">{status}</p>}{shareURL&&<input className="iwp-share-url" aria-label="Shareable instrument URL" value={shareURL} readOnly onFocus={e=>e.target.select()}/>}
  <details className="iwp-instrument-method"><summary>Model, source &amp; limits</summary><p>{config.method}</p>{config.source&&<a href={config.source} download>{config.sourceLabel} ↓</a>}<p>Drag to orbit; use the view and zoom buttons with a keyboard. Scroll over the 3D scene to zoom, or pinch on a touchscreen. Move the pointer outside the scene to scroll the article. Shared links restore controls; the camera starts from its standard view. Pinned comparisons preserve readouts.</p></details>
  <details className="iwp-instrument-static" open={staticOpen} onToggle={e=>setStaticOpen(e.currentTarget.open)}><summary>Open the 2D explanation / print view</summary><div className="iwp-static">{fallback}</div></details>
 </div>
}
